### ISSUE TITLE
cannot get clusters.tsv file?

### ISSUE THREAD

**Issue by ChaoXianSen** [RasmussenLab/vamb#220] opened 2023-10-10 10:10 UTC
Hi !
my run mode: ' vamb --outdir output63 \ 
                                   --fasta R63.contigs.fa.gz \
                                   --jgi R63_depth.txt \
                                   -o C '
why I cannot get the file 'clusters.tsv' ?

Thanks!

**Comment by jakobnissen** [comment] 2023-10-10 12:04
Closing as duplicate of #221

**Closed by jakobnissen** 2023-10-10 12:04 UTC
