### ISSUE TITLE
[Suggestion] Take the intersection of the TNF array and the RPKM when the former is a subset of the later

### ISSUE THREAD

**Issue by apcamargo** [RasmussenLab/vamb#34] opened 2020-08-04 19:56 UTC
I mapped my reads to the full metagenome assembly and computed the JGI coverage file using [CoverM](https://github.com/wwood/CoverM). Because I only want contigs >= 2000 bp to be processed by VAMB, I set `-m 2000`.

This causes an error because the TNF array (only long contigs) is shorter than the RPKM array (all contigs). A simple solution would be to map the reads only to a filtered metagenome with contigs  >= 2000 bp, however this would probably lead to suboptimal alignments and a worse estimation of coverages. My solution was to remove the short contigs from the JGI coverage file, but it would be nice if VAMB could deal with this kind of problem automatically.

A simple solution would be to subset the RPKM array, taking only the contigs that are present in the TNF array. I think this would require `load_jgi` to store and return contig names, which would increase memory usage a bit.

**Comment by jakobnissen** [comment] 2020-08-12 07:16
Dear @apcamargo 

It might be hard to do something sane and useful here on the Vamb side. TNF and RPKM are simple float matrices, and don't by themselves contain enough information to do the intersection - you need the names for that.

I do think that storing the names in both the TNF and RPKM array is unacceptable. First, because it consumes significant amounts of memory - and some Vamb users are already hard pressed for memory because they process millions of contigs. Second, because it means the TNF and RPKM objects would not be Numpy matrices anymore, but some wrapper type which contained both the names and the matrix - this makes operating on them just a little more annoying.

I could add a function that, given the two matrices, and two lists of names with contigs in the matrices, does the intersection. But would this really be helpful? If you have to construct the lists with contig names yourself, at that point couldn't you just do the intersection yourself?

In general, it's very difficult to pre-empt the various different formats that users of Vamb could get their data in (see e.g. issue #18). It's probably a much saner and simpler approach to just specify which format you need it in for Vamb, and then expect the user to deliver in that format.

**Comment by apcamargo** [comment] 2020-08-12 16:37
Yes, I agree with you. After I posted the suggestion I gave a look at the code and I saw that you only use numpy matrices (and rightfully so, in my opinion). Maybe the error message when `-m` is used could be improved to make it easier for the user to identify the problem.

**Comment by microbiomix** [comment] 2020-12-13 17:29
Hi, I would upvote this request. Especially in the case where `--fasta` is combined with `--bamfiles` or `--jgi`, names are included in both inputs, so it is easy to figure out in a preprocessing step. When I sent contigs with minimum length `1000bp` (via `--fasta`) and corresponding depth (via `--jgi`) and in addition set `-m 2500`, in fact VAMB subset the fasta file properly by length. Then it failed because the subset sequence data now did not match the input depth data. It took me some time to understand what the problem was, because both original input files matched, and it was the asymmetric subsetting within VAMB that caused this problem. It also complicates workflows when you want to try lowering contig lengths gradually and stop when performance is not acceptable anymore. E.g., in metabat2 you can keep the same input but just change the minimum length parameter and it subsets contigs in both sequence and depth spaces automatically. It would be great if this functionality could be added.
Thanks,
Mani

**Comment by jakobnissen** [comment] 2020-12-13 22:31
@microbiomix I have now made the `-m` option apply to parsing an input JGI file, and see also #40 . However, the original issue is still unresolved.

**Comment by apcamargo** [comment] 2020-12-14 19:28
Using hashes is a good solution to decrease memory usage, good idea.

@jakobnissen, if you think it might be useful I can try to adapt [pyCoverM](https://github.com/apcamargo/pycoverm) to Vamb's needs. It computes the exact same values as `jgi_summarize_bam_contig_depths`, but much faster (as I use CoverM as a backend) and all within Python (the code is actually compiled), so there's no need for external dependencies.

**Comment by jakobnissen** [comment] 2020-12-16 09:30
Yes, that would be great! I actually did try to emulate `jgi_summarize_bam_contig_depths` using `pysam`, after I found that it was more accurate that Vamb's built-in depths. Of course a Rust implementation with Python bindings would be far superior.

Honestly, you probably don't need to adapt pyCoverM at all. The output looks like something Vamb could use. As long as it's multithreaded and easy to use as a dependency. I'll take a look at it!

**Comment by jakobnissen** [comment] 2021-01-13 12:55
I'm closing this issue now. To summarize
* I won't automatically subset sequences, because it'll require too much memory
* Some of the issues were caused by Vamb incorrectly ignoring reference name hashes and not filtering for contig size when parsing JGI's output. That has been fixed
* The issue of switching to pycoverm is discussed in another issue.

You're welcome to re-open it if you think I missed something.

**Closed by jakobnissen** 2021-01-13 12:55 UTC

**Comment by apcamargo** [comment] 2021-01-13 15:06
Sure. I agree the memory costs are not worth it. Let's continue the discussion in the other issue thread.
