### ISSUE TITLE
log file ending

### ISSUE THREAD

**Issue by Lucas-Maciel** [RasmussenLab/vamb#76] opened 2021-06-30 09:08 UTC
Hi, 

I have a question about the log file. My file ended as indicated below,  should I've received more messages?

#vamb --outdir vamb_out --fasta catalogue.fna.gz --bamfiles bam/*.bam -o C --minfasta 200000
```


        Epoch: 498      Loss: 0.719027  CE: 3.7655156   SSE: 31.535543  KLD: 112.6330   Batchsize: 4096
        Epoch: 499      Loss: 0.719019  CE: 3.7654662   SSE: 31.534436  KLD: 112.6466   Batchsize: 4096
        Epoch: 500      Loss: 0.719029  CE: 3.7655594   SSE: 31.532504  KLD: 112.6236   Batchsize: 4096

        Encoding to latent representation
        Trained VAE and encoded in 338093.83 seconds

Clustering
        Windowsize: 200
        Min successful thresholds detected: 20
        Max clusters: None
        Min cluster size: 1
        Use CUDA for clustering: False
        Separator: "C"
```

These are the files generated in the output, my job had an exit status 1.
`clusters.tsv  latent.npz  lengths.npz  log.txt  mask.npz  model.pt  rpkm.npz  tnf.npz`

**Comment by jakobnissen** [comment] 2021-06-30 12:20
Yes indeed, that doesn't look right. How does stderr look?

**Comment by Lucas-Maciel** [comment] 2021-06-30 12:27
@jakobnissen the stderr and stdout files are empty. Just the log.txt has information.

By the job information it doesn't seem to be lack of memory

```
jobname      vamb.sh             
qsub_time    Fri Jun 25 15:10:26 2021
start_time   Fri Jun 25 15:10:29 2021
end_time     Wed Jun 30 05:08:26 2021
failed       0    
exit_status  1                   
mem          0.000Bs
maxvmem      239.894GB
arid         undefined
ar_sub_time  undefined
category     -q all.q -l mem_limit=400G 
```

Is there a way to run by the command line again without having to wait the 338093.83 seconds of training?

Thanks for your fast answer

**Comment by jakobnissen** [comment] 2021-06-30 13:24
I'm stumped as to what it could be, without any errors or stack traces. You can try to re-run it doing only 1 epoch, setting `-q` to the empty string, and loading the depths from the saved `depths.npz` file. Obviously this will not give you good results, but maybe there will be a stacktrace?

If you want to save your run, try to have a look at the tutorial in `doc/tutorial.html`. There should be a saved `latent.npz` file with the result from the training process that you can cluster "manually" by writing a Python script and importing Vamb.

**Comment by simonrasmu** [comment] 2021-07-08 14:40
@jakobnissen Maybe we should write a quick wrapper that can take latent.npz and contignames as input and cluster these?

**Comment by Lucas-Maciel** [comment] 2021-07-08 14:48
For now, I decided to run from scratch again and see if I'm gonna have the same issue. But if you could make this wrapper to continue from latent.npz intermediate file would be nice.

**Comment by jakobnissen** [comment] 2022-03-06 16:33
I'm wary of adding more "surface" to Vamb - that is, more code that needs to be maintained and tested with every release. I think the best thing do to here is just to close the issue until we get more information so that the issue is actionable.

**Closed by jakobnissen** 2022-03-06 16:33 UTC
