### ISSUE TITLE
VAMB program, ValueError: BAM file

### ISSUE THREAD

**Issue by ChaoXianSen** [RasmussenLab/vamb#225] opened 2023-10-13 08:52 UTC
Dear @jakobnissen 

I'm running vamb v3.0.2 with python 3.7  using the following command:

vamb --outdir output63_vamb \
        --fasta R63.contigs.fa \
        --bamfiles R63_sort.bam

**How files 'R63.contigs.fa'and  'R63_sort.bam' are obtained:** 
How to get the file 'R63.contigs.fa'  :
      megahit \
		-1 R63_kneaddata_paired_1.fastq \
		-2 R63_kneaddata_paired_2.fastq \
		-o 03_megahit/R63 \
		--out-prefix R63

How to get the file 'R63_sort.bam'  :
        bowtie2 \
		--threads 8 \
		-x index/R63 \
		-1 R63_kneaddata_paired_1.fastq \
		-2 R63_kneaddata_paired_2.fastq \
		| $samtools sort -@ 4 -O bam -o - > R63_sort.bam

**run vamb program,  err report:**

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/public/home/p282664/miniconda3/envs/vamb/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/public/home/p282664/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/parsebam.py", line 253, in _get_contig_rpkms
    _check_bamfile(inpath, bamfile, refhash, minlength)
  File "/public/home/p282664/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/parsebam.py", line 221, in _check_bamfile
    raise ValueError(errormsg.format(path, hash.hex(), refhash.hex()))
ValueError: BAM file ./R63_sort.bam has reference hash 2a7c047eaa255f96baa5e7bf8861ed72, expected c03b5d5399b876c3ebdd348b5c66a2fb. Verify that all BAM headers and FASTA headers are identical and in the same order.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/public/home/p282664/miniconda3/envs/vamb/bin/vamb", line 11, in <module>
    sys.exit(main())
  File "/public/home/p282664/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 528, in main
    logfile=logfile)
  File "/public/home/p282664/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 247, in run
    len(tnfs), minalignscore, minid, subprocesses, logfile)
  File "/public/home/p282664/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 115, in calc_rpkm
    subprocesses=subprocesses, logfile=logfile)
  File "/public/home/p282664/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/parsebam.py", line 340, in read_bamfiles
    process.get()
  File "/public/home/p282664/miniconda3/envs/vamb/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: BAM file ./R63_sort.bam has reference hash 2a7c047eaa255f96baa5e7bf8861ed72, expected c03b5d5399b876c3ebdd348b5c66a2fb. Verify that all BAM headers and FASTA headers are identical and in the same order.

Any idea about this problem?

Thanks!

**Comment by jakobnissen** [comment] 2023-10-13 10:51
As the error states, it looks like the identifiers (headers) in your FASTA file is not the same as those in the BAM file.
I would first verify that the identifiers are the same: Here's how:

* Get the BAM identifiers with `samtools view -H myfile.bam | grep @SQ | cut -b 8- | cut -f 1 > bam_identifiers`
* Get the FASTA identifiers with ` grep -oE '^>\S+' fasta.fna | cut -b 2- > fasta_identifiers`
* Compare with `diff fasta_identifiers bam_identifiers`'

I would also note that we have already improved the error message, but this improvement has not yet made it into the newest release.

**Comment by ChaoXianSen** [comment] 2023-10-13 11:15
Dear @jakobnissen ,thanks for your response!

Following your suggestion, I went to have a try:

head R63_sort_bam_identifiers: 
k141_514373
k141_0
k141_342916
k141_85729
k141_1
k141_257187
k141_600101
k141_2
k141_514374
k141_85730

head R63_contigs_fasta_identifiers:
k141_514373
k141_0
k141_342916
k141_85729
k141_1
k141_257187
k141_600101
k141_2
k141_514374
k141_85730

diff R63_contigs_fasta_identifiers R63_sort_bam_identifiers              # there is no prompt message

The identifiers are the same, there is no difference between the two files. 

Any idea about this problem?  I don't quite understand  the previous error report ~

thanks!

**Comment by ChaoXianSen** [comment] 2023-10-13 17:22
Maybe you can use the following two files: 
contigs file :  https://drive.google.com/file/d/1s9zOQnPp9yEygeJcWNcCM2VUJJla66Ln/view?usp=sharing
BAM file : https://drive.google.com/file/d/17E8LbtzF6MJVmq5IlR8OFq3PAsGrB2k6/view?usp=sharing

Looking forward to you reply ! thanks a lot !

**Comment by jakobnissen** [comment] 2023-10-14 19:27
I can reproduce this on Vamb 3.0.2, but not on the later versions.
I'll dig into it Monday, but for now, you can try to install the latest version (v 4.1.3).

**Comment by jakobnissen** [comment] 2023-10-15 11:35
Okay, I found the reason for the problem. Indeed, the headers in your BAM file are different from those in the FASTA file. You can use `samtools view` to see for yourself.
For example, the first header in your `contigs.fna` is: `k141_514373 flag=1 multi=3.0000 len=356`, whereas the first one in the BAM file is `141_514373`.
In older versions of Vamb, Vamb would compare the headers as-is, that's why you get the error. In newer versions, Vamb only looks at the first "word" in the header, since this is the only thing that appears in the BAM files.
Hence, if you don't want to upgrade Vamb, you can resolve this error by making sure there are no spaces in the headers of the FASTA file, such that the first word of the headers (present in the BAM files) is the same as the whole header (as read from the FASTA file).

Closing as solved.

**Closed by jakobnissen** 2023-10-15 11:35 UTC

**Comment by ChaoXianSen** [comment] 2023-10-16 01:21
Dear @jakobnissen 
I willl replace the space in the header and try again .

Thanks for your help !
