### ISSUE TITLE
KeyError: "Separator 'C' not in sequence label: 'k119_1704'"

### ISSUE THREAD

**Issue by amirshams84** [RasmussenLab/vamb#36] opened 2020-10-10 13:35 UTC
` vamb --outdir ./vamb --fasta ./megahit_contigs_trim.fasta --bamfiles ./*.bam -o C --minfasta 200000`

Vamb give the following error

`KeyError: "Separator 'C' not in sequence label: 'k119_1704'"`

Any suggestion?

**Comment by jakobnissen** [comment] 2020-10-11 20:04
Hello @amirshams84 

The answer can be found in Vamb's readme:
> Your contig headers must be unique. Furthermore, if you want to use binsplitting (and you should!), your contig headers must be of the format {Samplename}{Separator}{X}, such that the part of the string before the first occurrence of {Separator} gives a name of the sample it originated from. For example, you could call contig number 115 from sample number 9 "S9C115", where "S9" would be {Samplename}, "C" is {Separator} and "115" is {X}.

The problem occurs if you attempt to split the contig names with the separator `C` (e.g. using the argument `-o C` from command line), but without the character "C" actually being the separator in your contig names.

More generally, Vamb *in itself* has no way of knowing which contig came from which same. The way to give that information to the sample is to name your contigs according to the samplename - see the quote above. Alternatively, if *you* don't have that information either, just don't do binsplitting (that is, omit `-o C`).

Closing this issue as resolved, but you're welcome to reopen or ping me if you think the issue is not resolved.

**Closed by jakobnissen** 2020-10-11 20:04 UTC
