### ISSUE TITLE
Last batch size exceeds dataset length

### ISSUE THREAD

**Issue by WEIGUO93** [RasmussenLab/vamb#116] opened 2022-05-18 08:50 UTC
Dear vamb support team,

### When I run ：
vamb --outdir /mnt/san3/usr/wg/arabidopsis/output/vam_AD02802_result --fasta /mnt/san3/usr/wg/arabidopsis/output/AD02802.fna.gz --bamfiles /mnt/san3/usr/wg/arabidopsis/output/AD02802.bam -o C 
--minfasta 200000

### vamb appears ：
[E::idx_find_and_load] Could not retrieve index file for '/mnt/san3/usr/wg/arabidopsis/output/AD02802.bam'
Traceback (most recent call last):
  File "/home/wg/anaconda3/bin/vamb", line 8, in <module>
    sys.exit(main())
  File "/home/wg/anaconda3/lib/python3.8/site-packages/vamb/__main__.py", line 501, in main
    run(args.outdir,
  File "/home/wg/anaconda3/lib/python3.8/site-packages/vamb/__main__.py", line 252, in run
    mask, latent = trainvae(outdir, rpkms, tnfs, nhiddens, nlatent, alpha, beta,
  File "/home/wg/anaconda3/lib/python3.8/site-packages/vamb/__main__.py", line 151, in trainvae
    vae.trainmodel(dataloader, nepochs=nepochs, lrate=lrate, batchsteps=batchsteps,
  File "/home/wg/anaconda3/lib/python3.8/site-packages/vamb/encode.py", line 467, in trainmodel
    raise ValueError('Last batch size exceeds dataset length')
ValueError: Last batch size exceeds dataset length

**Comment by jakobnissen** [comment] 2022-05-18 09:11
Duplicate of #117. Closing

**Closed by jakobnissen** 2022-05-18 09:11 UTC
