### ISSUE TITLE
parsebam.py failing

### ISSUE THREAD

**Issue by Guillaume-Marseille** [RasmussenLab/vamb#190] opened 2023-07-24 10:41 UTC
Hello
I'm posting this message because I'm encountering a problem that I can't explain.

**when I run this command:**

`vamb --outdir /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/VAMB --fasta MEGAHIT.all.contigs.2000.CDH --bamfiles /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/*.bam`

**I get this error:**

`[E::idx_find_and_load] [E::idx_find_and_load] Could not retrieve index file for '/shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/03ENR.UV.bam'Could not retrieve index file for '/shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/03ENR.MV.bam'

[E::idx_find_and_load] [E::idx_find_and_load] Could not retrieve index file for '/shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/04ENR.UV.bam'Could not retrieve index file for '/shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/05EDM.MV.bam'

[E::idx_find_and_load] [E::idx_find_and_load] Could not retrieve index file for '/shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/03EDM.MV.bam'Could not retrieve index file for '/shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/03EDM.UV.bam'

[E::idx_find_and_load] [E::idx_find_and_load] Could not retrieve index file for '/shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/04EDM.MV.bam'Could not retrieve index file for '/shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/04ENR.MV.bam'

[E::idx_find_and_load] [E::idx_find_and_load] Could not retrieve index file for '/shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/06EDM.MV.bam'Could not retrieve index file for '/shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/07EDM.MV.bam'

[E::idx_find_and_load] Could not retrieve index file for '/shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/05ENR.UV.bam'
[E::idx_find_and_load] Could not retrieve index file for '/shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/05ENR.MV.bam'
[E::idx_find_and_load] Could not retrieve index file for '/shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/07ENR.MV.bam'
[E::idx_find_and_load] Could not retrieve index file for '/shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/06EDM.UV.bam'
[E::idx_find_and_load] Could not retrieve index file for '/shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/06ENR.UV.bam'
[E::idx_find_and_load] Could not retrieve index file for '/shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/06ENR.MV.bam'
[E::idx_find_and_load] Could not retrieve index file for '/shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/07ENR.UV.bam'
Vamb aborted due to error in subprocess. See stacktrace for source of exception.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/shared/ifbstor1/software/miniconda/envs/vamb-3.0.2/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/shared/ifbstor1/software/miniconda/envs/vamb-3.0.2/lib/python3.7/site-packages/vamb/parsebam.py", line 253, in _get_contig_rpkms
    _check_bamfile(inpath, bamfile, refhash, minlength)
  File "/shared/ifbstor1/software/miniconda/envs/vamb-3.0.2/lib/python3.7/site-packages/vamb/parsebam.py", line 221, in _check_bamfile
    raise ValueError(errormsg.format(path, hash.hex(), refhash.hex()))
ValueError: BAM file /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/03EDM.MV.bam has reference hash 4645f4bd9ca8f9a43d898b80eb3f8e25, expected 83c2d70cd1e552a1a209942cb9112b6f. Verify that all BAM headers and FASTA headers are identical and in the same order.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/shared/ifbstor1/software/miniconda/envs/vamb-3.0.2/bin/vamb", line 11, in <module>
    sys.exit(main())
  File "/shared/ifbstor1/software/miniconda/envs/vamb-3.0.2/lib/python3.7/site-packages/vamb/__main__.py", line 528, in main
    logfile=logfile)
  File "/shared/ifbstor1/software/miniconda/envs/vamb-3.0.2/lib/python3.7/site-packages/vamb/__main__.py", line 247, in run
    len(tnfs), minalignscore, minid, subprocesses, logfile)
  File "/shared/ifbstor1/software/miniconda/envs/vamb-3.0.2/lib/python3.7/site-packages/vamb/__main__.py", line 115, in calc_rpkm
    subprocesses=subprocesses, logfile=logfile)
  File "/shared/ifbstor1/software/miniconda/envs/vamb-3.0.2/lib/python3.7/site-packages/vamb/parsebam.py", line 340, in read_bamfiles
    process.get()
  File "/shared/ifbstor1/software/miniconda/envs/vamb-3.0.2/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: BAM file /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/03EDM.MV.bam has reference hash 4645f4bd9ca8f9a43d898b80eb3f8e25, expected 83c2d70cd1e552a1a209942cb9112b6f. Verify that all BAM headers and FASTA headers are identical and in the same order.
`

**I did check and confirm that BAM headers and FASTA headers are identical and in the same order. 
So I'm wondering where the error might have come from, but it's not obvious.
Any help would be highly appreciated
Thanks
Guillaume**

**The bam files have been generated using commands like this one:**

`minimap2 -t 12 -N 5 -ax sr --split-prefix /tmp/mmsplit.4 /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/CATALOGUE.CONTIGS.mmi /tmp/03ENR.UV_R1.fastq.gz /tmp/03ENR.UV_R2.fastq.gz`

**The content of the log.txt file:**

`Starting Vamb version 3.0.2
        Date and time is 2023-07-24 12:23:10.909347

Loading TNF
        Minimum sequence length: 100
        Loading data from FASTA file MEGAHIT.all.contigs.2000.CDH

        Kept 1921342275 bases in 309704 sequences
        Processed TNF in 53.65 seconds

Loading RPKM
        Parsing 17 BAM files with 8 subprocesses
        Reference hash: 83c2d70cd1e552a1a209942cb9112b6f
        Min alignment score: None
        Min identity: None
        Min contig length: 100
        
Order of columns is:
        /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/03EDM.MV.bam
        /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/03EDM.UV.bam
        /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/03ENR.MV.bam
        /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/03ENR.UV.bam
        /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/04EDM.MV.bam
        /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/04ENR.MV.bam
        /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/04ENR.UV.bam
        /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/05EDM.MV.bam
        /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/05ENR.MV.bam
        /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/05ENR.UV.bam
        /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/06EDM.MV.bam
        /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/06EDM.UV.bam
        /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/06ENR.MV.bam
        /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/06ENR.UV.bam
        /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/07EDM.MV.bam
        /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/07ENR.MV.bam
        /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/07ENR.UV.bam

        ERROR WHEN PROCESSING: /shared/projects/phycovir/ULVE/VIROME-ASSEMBLIES/VAMB-BINNING.2/MINIMAP/03EDM.MV.bam
`

**Comment by jakobnissen** [comment] 2023-07-24 12:01
Thanks for the bug report. I'll review the relevant code, but usually I would need to be able to reproduce the error to fix it.
For that, I would need the FASTA file and the offending BAM file. If they are too large to share (or secret), if you could recreate the problem with a smaller file, that would be grand.
I will see if I can implement a better error message on a new branch. Then, you can try running Vamb from that new branch and see if the improved error message tells you anything new.

**Comment by jakobnissen** [comment] 2023-07-24 12:19
@Guillaume-Marseille If you can't create an example for me to test, could you try re-running Vamb with the new refhash_err branch?

**Comment by jakobnissen** [comment] 2023-08-14 08:56
@Guillaume-Marseille I've now merged the refhash_err branch into Vamb's master branch, so any future releases of Vamb should have improved error messages for this message in particular.
When reviewing the code, I did not see any bugs that could cause this issue.

**Comment by jakobnissen** [comment] 2023-10-15 12:06
Dear @Guillaume-Marseille 
I believe I've found the reason for the problem, see https://github.com/RasmussenLab/vamb/issues/225#issuecomment-1763362080
Closing as solved. Please re-open if I'm wrong.

**Closed by jakobnissen** 2023-10-15 12:06 UTC
