### ISSUE TITLE
'BAM file[...]must be unsorted or sorted by readname.'

### ISSUE THREAD

**Issue by nvpatin** [RasmussenLab/vamb#146] opened 2023-03-13 21:38 UTC
I used minimap2 to map interleaved reads to a concatenated fasta file, where contigs from each individual assembly were named according to the source sample. I then sorted the bam files with samtools sort. When I run Vamb using the sorted bam files, I get the following Traceback: 

ValueError: BAM file 1903buk1_0m-2_sorted.bam is marked with sort order 'coordinate', must be unsorted or sorted by readname.

But according to the documentation, bams must be sorted by coordinate! Could it have something to do with the reads being interleaved rather than separate forward and reverse files?

I am using samtools v. 1.6, minimap2 v. 2.24-r1122, and the most recent version of vamb when installed with conda.

**Comment by jakobnissen** [comment] 2023-03-16 09:07
Whoops sorry for the late answer.
The issue is that you've caught this repository in an awkward transition period - we're just about to release version 4.0.0, but got delayed a few weeks. Hence, the master branch of the repo shows the documentation for Vamb 4, but you probably have Vamb 3 installed.
In version 4, we switched the abundance computation to use CoverM, which needs BAM files sorted by coordinate, not name, whereas in the old v3,  we need them sorted by readname.

Your options are
* Keep the BAM files unsorted (or sorted by read name) and keep using v3
* Install Vamb 4 from the master branch of this repository. Vamb4 is more robust and gives slightly better binning results.

Closing as solved, but you're welcome to re-open or open another issue.

**Closed by jakobnissen** 2023-03-16 09:07 UTC

**Comment by nvpatin** [comment] 2023-03-20 15:54
Thanks @jakobnissen, I installed Vamb 4 from the master branch using pip but got a numpy error:
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

  * The Python version is: Python3.11 from "/work/nvp29/miniconda3/envs/vamb/bin/python3.11"
  * The NumPy version is: "1.19.1"

What is the required numpy version for Vamb 4?
